services:
  postgres:
    image: postgres:17-alpine
    container_name: postgresTask
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    container_name: redisTask
    image: redis:8.0.1-alpine
    command: redis-server --requirepass redispassword
    restart: unless-stopped
    ports:
      - "6379:6379"

  rabbit:
    container_name: rabbit
    image: rabbitmq:4.1.0-management-alpine
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  pgdata:
