services:
#  app:
#    build: .
#    container_name: task-app
#    ports:
#      - '${PORT}:${PORT}'
#    env_file:
#      - .env
#    environment:
#      POSTGRES_HOST: ${POSTGRES_HOST}
#      POSTGRES_PORT: ${POSTGRES_PORT}
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_DB: ${POSTGRES_DB}
#      NODE_ENV: ${NODE_ENV}
#      PORT: ${PORT}
#    depends_on:
#      - postgres

  postgres:
    image: postgres:17-alpine
    container_name: postgresTask
    restart: always
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: