services:
  postgres:
    image: postgres:17-alpine
    container_name: postgresTask
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    container_name: redisTask
    image: redis:8.0.1-alpine
    command: redis-server --requirepass redispassword
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata:
