services:
  postgres:
    image: postgres:17-alpine
    container_name: postgresTask
    restart: unless-stopped
    env_file:
      .env
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    container_name: redisTask
    image: redis:8.0.1-alpine
    command: redis-server --requirepass redispassword
    restart: unless-stopped
    ports:
      - "6379:6379"

  rabbit:
    container_name: rabbit
    image: rabbitmq:4.1.0-management-alpine
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"

  nestjs:
    container_name: nestjsTask
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
      - rabbit
    env_file:
      .env

volumes:
  pgdata:
